apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: task-board
  labels:
    app.kubernetes.io/name: task-board
    app.kubernetes.io/component: configuration
data:
  NODE_ENV: "production"
  APP_NAME: "DevOps Task Board"
  APP_VERSION: "1.0.0"
  LOG_LEVEL: "info"
  PROMETHEUS_ENABLED: "true"
  JAEGER_ENABLED: "true"
  API_TIMEOUT: "30000"
  MAX_CONNECTIONS: "100"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: task-board
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/component: database
data:
  POSTGRES_DB: "taskboard"
  POSTGRES_MAX_CONNECTIONS: "100"
  POSTGRES_SHARED_BUFFERS: "256MB"
  POSTGRES_EFFECTIVE_CACHE_SIZE: "1GB"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
  namespace: task-board
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/component: cache
data:
  redis.conf: |
    maxmemory 256mb
    maxmemory-policy allkeys-lru
    save 900 1
    save 300 10
    save 60 10000
    appendonly yes
    appendfsync everysec
