apiVersion: v1
kind: Namespace
metadata:
  name: task-board
  labels:
    name: task-board
    environment: development
    app.kubernetes.io/name: task-board
    app.kubernetes.io/instance: task-board-dev
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/component: application
    app.kubernetes.io/part-of: devops-showcase
    app.kubernetes.io/managed-by: kubectl
  annotations:
    description: "DevOps Showcase Task Board Application"
    owner: "devops-team"
    cost-center: "engineering"
---
# Resource Quota for namespace
apiVersion: v1
kind: ResourceQuota
metadata:
  name: task-board-quota
  namespace: task-board
spec:
  hard:
    requests.cpu: "2"
    requests.memory: 4Gi
    limits.cpu: "4"
    limits.memory: 8Gi
    persistentvolumeclaims: "5"
    services: "10"
    secrets: "10"
    configmaps: "10"
---
# Limit Range for pods
apiVersion: v1
kind: LimitRange
metadata:
  name: task-board-limits
  namespace: task-board
spec:
  limits:
  - default:
      cpu: 500m
      memory: 512Mi
    defaultRequest:
      cpu: 100m
      memory: 128Mi
    type: Container
