apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: task-board
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/component: database
type: Opaque
data:
  # echo -n 'taskuser' | base64
  username: dGFza3VzZXI=
  # echo -n 'taskpass' | base64  
  password: dGFza3Bhc3M=
  # echo -n 'taskboard' | base64
  database: dGFza2JvYXJk
---
apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
  namespace: task-board
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/component: cache
type: Opaque
data:
  # Redis password (empty for demo)
  password: ""
---
apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: task-board
  labels:
    app.kubernetes.io/name: task-board
    app.kubernetes.io/component: application
type: Opaque
data:
  # echo -n 'super-secret-jwt-key-for-production-change-this' | base64
  jwt-secret: c3VwZXItc2VjcmV0LWp3dC1rZXktZm9yLXByb2R1Y3Rpb24tY2hhbmdlLXRoaXM=
  # echo -n 'session-secret-key-change-in-production' | base64
  session-secret: c2Vzc2lvbi1zZWNyZXQta2V5LWNoYW5nZS1pbi1wcm9kdWN0aW9u
